project_name: waffle

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/waffle/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/tacheshun/waffle/internal/version.Version={{.Version}} -X github.com/tacheshun/waffle/internal/version.Commit={{.ShortCommit}} -X github.com/tacheshun/waffle/internal/version.Date={{.Date}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - docs/**/*
      - examples/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: tacheshun
    name: waffle
  prerelease: auto
  draft: false
  name_template: "Waffle {{.Version}}"

brews:
  - repository:
      owner: tacheshun
      name: homebrew-tools
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    homepage: https://github.com/tacheshun/waffle
    description: Lightweight Web Application Firewall (WAF) written in Go
    license: MIT
    test: |
      system "#{bin}/waffle --version"
    install: |
      bin.install "waffle" 